---

- name: mediawiki | Install wikimedia extensions
  git:
    repo: "{{ mediawiki_extensions_base_url }}/{{ item }}"
    dest: "{{ mediawiki_extensions_dir }}/{{ item }}"
    version: "{{ mediawiki_release }}"
    force: "{{ mediawiki_git_force }}"
  with_items: "{{ mediawiki_extensions_wikimedia }}"
  when: mediawiki_extensions_wikimedia is defined
  tags: extensions

- name: mediawiki | Make extensions directory readable
  file:
    path: "{{ mediawiki_extensions_dir }}"
    mode: "{{ mediawiki_file_mode }}"
    recurse: yes
  tags: extensions
